### ISSUE TITLE
AE2 Autocrafting crash/timeout with ProjectE

### ISSUE THREAD

**Issue by DeltaCore** [FTBTeam/FTB-Sky-Odyssey#207] opened 2019-03-24 15:26 UTC
* **Modpack Version**: 1.0.0

* **Issue**: Timout when trying to autocraft something.

I looked for a similar problem in the issues but could not find one that matched what i was experiencing.

The setup: Compressed Refined EMC Link providing Gold and Redstone via a storage bus to the AE2 network. Autocrafting recipies for the AE2 Processors are in place in interfaces attached to advanced inscribers.

When ever i want to autocraft anything: I select the item in the AE2 terminal i want to craft, select 1 item and then hit next. Nothing happens, after about 15-30sec later i get a timeout. When i reconnect the item is not crafted or anything.

The server log shows no error what so ever. One time i had the server crash from this and i was able to recover the crash logs from that one.

* **Link to Log or Crash File Paste**: 
"Timeout" log - https://paste.feed-the-beast.com/view/aa8298b8
"Server Crash" log 1 - https://paste.feed-the-beast.com/view/685f271c
"Server Crash" log 2 - https://paste.feed-the-beast.com/view/1db72dbc

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2, ProjectE

* **Known Fix**: Nothing

I can provide you with my worldfile if that helps. I can upload it so you can test that aswell.
If there is anything i can provide you that will help track down the issue, i am happy to help you with that.

Kind regards,
Marcel

**Comment by EAJ97** [comment] 2019-03-24 18:09
I have the exact same issue. It seems like trying to autocraft anything that isnt EMC-able that uses any EMC items really screws with the server and crashes it. https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/198#issue-424564887

**Comment by MrGcGamer** [comment] 2019-03-25 11:13
Same for me but the server crashes every time I try to autocraft something with emc link (even if the output also has emc)

**Comment by Naxanria** [comment] 2019-03-25 17:04
duplicate of #198

**Closed** 2019-03-25 17:04 UTC
Labels: duplicate
