### ISSUE TITLE
Stoneburnt Chicken Spawn Egg

### ISSUE THREAD

**Issue by SigmaLP** [FTBTeam/FTB-Sky-Odyssey#238] opened 2019-03-27 15:43 UTC
* **Modpack Version**: 1.0.0

* **Issue**: "Base/Vanilla" Chicken from Hatchery/Roost(at work and cannot remember which mod it is) not recognized as valid for crafting the Stoneburnt Chicken Spawn Egg.  I was using the Marble Crafting table. 

* **Link to Log or Crash File Paste**: N/A

* **Mod/s Affected**: Hatchery/Roost

Hope this is sufficient, thanks!

**Comment by dsabecky** [comment] 2019-03-28 10:55
Can confirm. Attempted to craft via Refined Storage, marble crafting table, and vanilla crafting table. Additionally, when using crafting autocomplete, the Roost chicken shows as not valid, however its the only chicken (screenshot 2)

![image](https://user-images.githubusercontent.com/778367/55152054-f6eedd80-5125-11e9-9b98-846ce9117d7c.png)

![2019-03-28_06 52 24](https://user-images.githubusercontent.com/778367/55152295-6e247180-5126-11e9-9717-47635895f636.png)

**Comment by SephirothWS** [comment] 2019-03-28 12:24
This is a duplicate of #172 because there's a typo in scripts/chickens.sz 

The script currently reads as

`#Add recipe for Stoneburnt Chicken recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "morechickens:stoneburntchicken"}}), [ [<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>], [<roost:chicken>.withTag({Chicken: "redstonecrystalchicken"}),<minecraft:egg>,<roost:chicken>.withTag({Chicken: "chickens:goldchicken"})], [<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>] ] );`

The redstone crystal chicken NBT tag is missing the modid to make it a valid chicken. The fix would be to add in the morechickens: modid to that NBT tag and it'll become craftable.

`#Add recipe for Stoneburnt Chicken recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "morechickens:stoneburntchicken"}}), [ [<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>], [<roost:chicken>.withTag({Chicken: "morechickens:redstonecrystalchicken"}),<minecraft:egg>,<roost:chicken>.withTag({Chicken: "chickens:goldchicken"})], [<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>] ] );`

**Comment by Kyra1509** [comment] 2019-03-31 01:12
If the above post is a fix, could the process please be explained in more detail for me? I'm unsure of where to go to find this coding and if a simple copy/paste could be used etc.  TIA :)

**Comment by LatvianModder** [comment] 2019-03-31 01:26
I think this was fixed already

**Closed** 2019-04-05 15:56 UTC
Labels: fixed in dev

**Comment by jayshoo** [comment] 2019-04-08 02:04
for future searchers looking to fix the FTB Sky Odyssey Stoneburnt Chicken spawn egg being uncraftable, open `Instances\FTB Sky Odyssey\scripts\chickens.zs` and edit line `454` as follows:

```diff
   #Add recipe for Stoneburnt Chicken
    recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "morechickens:stoneburntchicken"}}),
	[
		[<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>],
-		[<roost:chicken>.withTag({Chicken: "redstonecrystalchicken"}),<minecraft:egg>,<roost:chicken>.withTag({Chicken: "chickens:goldchicken"})],
+		[<roost:chicken>.withTag({Chicken: "morechickens:redstonecrystalchicken"}),<minecraft:egg>,<roost:chicken>.withTag({Chicken: "chickens:goldchicken"})],
		[<extrautils2:decorativesolid:3>,<minecraft:wheat_seeds>,<extrautils2:decorativesolid:3>]
	]
);
```
