### ISSUE TITLE
Crash Report: 16/04/2019, Status of cause: Unknown

### ISSUE THREAD

**Issue by LlamaMilk** [FTBTeam/FTB-Sky-Odyssey#357] opened 2019-04-16 15:30 UTC
[crash-2019-04-15_17.28.48-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3085628/crash-2019-04-15_17.28.48-client.txt)
* **Modpack Version**:  1.1.0 Beta
* **Issue**: When i launch my world it loads for like a second and goes to sky only then crashes

* **Link to Log or Crash File Paste**: https://pastebin.com/iiuqa6nE

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: Maybe EnderIO or the "new"translocator thingys

* **Known Fix**: I do not know how to fix im sorry

**Comment by LumberWizard** [comment] 2019-04-16 17:15
See https://github.com/SleepyTrousers/EnderIO/issues/5086, fix in https://github.com/Vazkii/Botania/commit/1701732aaccb02279b64ceeef3d6a0c0409a3bf5, Botania version https://minecraft.curseforge.com/projects/botania/files/2698039

**Comment by Naxanria** [comment] 2019-04-17 08:47
Duplicate of #353

**Closed as completed by Naxanria** 2019-04-17 08:47 UTC
Labels: duplicate
