### ISSUE TITLE
stuck loading 

### ISSUE THREAD

**Issue by gameking79** [FTBTeam/FTB-Sky-Odyssey#297] opened 2019-04-06 09:46 UTC
my game keeps loading on the mod let's encrypt craft when i start up my game

![loading](https://user-images.githubusercontent.com/49314077/55667812-9700e100-5861-11e9-960e-20a85cf978ba.png)

**Comment by nzminecraftDOTcom** [comment] 2019-04-06 09:59
How much ram have you allocated to the game through the FTB/Twitch launcher?

**Comment by gameking79** [comment] 2019-04-06 10:00
9GB

**Comment by Naxanria** [comment] 2019-04-06 10:45
Duplicate of #294

**Closed as completed** 2019-04-06 10:47 UTC
Labels: duplicate

**Comment by gameking79** [comment] 2019-04-06 11:29
stop closing this it isnt fixed bro

**Comment by Naxanria** [comment] 2019-04-07 10:08
I closed other one by accident, reopened it and waiting for more info there.
