### ISSUE TITLE
Spawn Eggs can be made with Mob Grinding Utils

### ISSUE THREAD

**Issue by moustachemuskrat** [FTBTeam/FTB-Sky-Odyssey#232] opened 2019-03-27 00:25 UTC
* **Modpack Version**: 1.0.0

* **Issue**: You can cheat the spawn egg quests with the GM chicken feed from mob grinding utils. Not sure if this is supposed to happen,

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mob grinding utils

**Comment by sreekrishn** [comment] 2019-03-27 05:00
the GM chicken feed can be gotten thru mob swab which is juz 2 wool and a stick

**Comment by Naxanria** [comment] 2019-03-27 12:10
Duplicate of https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/111

**Closed** 2019-03-27 12:10 UTC
Labels: duplicate
