### ISSUE TITLE
Refined Storage 1k disk drives stored in ProjectE aren't usable

### ISSUE THREAD

**Issue by kkewl** [FTBTeam/FTB-Sky-Odyssey#245] opened 2019-03-28 14:02 UTC
* **Modpack Version**:  1.0.0

* **Issue**: Created 1k storage drives for Refined Storage.  Stored them as EMC.  As I pull them out they are not usable in disk drive.  the 1k storage parts are usable to build a storage drive that works, but not the completed product.  No errors, just wont take the item.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Refined Storage, ProjectE

* **Known Fix**: Work Around, store the 1k storage part as EMC then craft drive.

**Comment by Wastl-B** [comment] 2019-03-29 15:47
This is already known and a dupe to [#192](https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/193)

**Comment by Naxanria** [comment] 2019-03-30 18:06
Duplicate of 192.

**Closed by Naxanria** 2019-03-30 18:06 UTC
Labels: duplicate
