### ISSUE TITLE
Crashed when picking up ion sniper from small crate

### ISSUE THREAD

**Issue by ColtonMak** [FTBTeam/FTB-Sky-Odyssey#240] opened 2019-03-27 20:55 UTC
* **Modpack Version**: v1.0.0

* **Issue**: Went to my automated mob farm and picked up a ion sniper from Matter Overdrive mod from a small storage crate from Actually Additions mod. The game froze and started to shut down the internal server before crashing.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e69b7959

* **Is it Repeatable?**: Upon reopening sky odyssey, the game will work for a couple seconds or so before crashing again.

* **Mod/s Affected**: Matter Overdrive mod (purely my opinion as there is a small chance that it is caused by another mod that I am unaware of)

* **Known Fix**: Placing the ion sniper back into the small crate immediately after opening sky odyssey seems to prevent the crash.

**Comment by dsabecky** [comment] 2019-03-28 10:46
Duplicate of issue #230

**Comment by dsabecky** [comment] 2019-03-28 10:50
Similar to issue #54 and issue #241

**Comment by Naxanria** [comment] 2019-04-08 10:26
This has been fixed in next update; The mod is removed.

**Closed by Naxanria** 2019-04-08 10:26 UTC
Labels: Sent to mod author, duplicate
