### ISSUE TITLE
Crashlog from emc link

### ISSUE THREAD

**Issue by xSquibbyx** [FTBTeam/FTB-Sky-Odyssey#138] opened 2019-03-21 14:19 UTC
* **1.0**: 

* **Crafting crash with emc link**: Went to craft interfaces and this crash occured 

* **https://paste.feed-the-beast.com/view/69a7cafc**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Rushmead** [comment] 2019-03-21 14:22
This is a duplicate of #84

**Closed** 2019-03-21 14:27 UTC
Labels: duplicate

**Comment by csonyi** [comment] 2019-03-21 14:29
Read up about it, it may has something to do with AE2 not liking it if an inventory has huge amounts of items in it (like the EMC links having as many as you can produce with your current amount in your network for each item).
A plausible fix could be giving the EMC links a maximum amount to provide so AE2 doesnt get confused? Like Integer cap or smth?

**Comment by Jake-E** [comment] 2019-03-21 14:30
Please continue the discussion in #84
