### ISSUE TITLE
PROBLEM MINECRAFT FTB SKY ODYSSEY NBT TO BIG

### ISSUE THREAD

**Issue by Abbasxd** [FTBTeam/FTB-Sky-Odyssey#282] opened 2019-04-03 20:08 UTC
Hi, i ran into some problems with my friends tonight. I played minecraft on Ftb Odyssey and suddenly the server crashed. Everyone else got in just fine after the server started up again. But i couldnt. Everytime i tried to join, it said 

![HALLÅ](https://user-images.githubusercontent.com/49252244/55509626-af53de80-565c-11e9-9aa3-f500e15ce333.png)

And the whole server dced, everytime i tried to join. 

my friend tried removing everything in my profiles inventory and deleting my spawnpoint. nothing works. I tried reinstalling FtB aswell 2 times. And nothing works. Please help!

**Comment by nzminecraftDOTcom** [comment] 2019-04-04 07:56
An item on your player, or where you are logging in has either stacked inside itself, or has you have a shulkerbox full of nbt named items, stacked inside other means of storage.

**Comment by Naxanria** [comment] 2019-04-04 16:27
duplicate of #85 and #178. This seems a vanilla issue we cant do anything about.

**Closed by Naxanria** 2019-04-04 16:27 UTC
