### ISSUE TITLE
Freeze "Waiting for server" when autocrafting with Applied Energistics 2

### ISSUE THREAD

**Issue by Killersdaddy** [FTBTeam/FTB-Sky-Odyssey#250] opened 2019-03-28 22:09 UTC
* **Modpack Version**: 1.0.0 i guess

I`ve seen similar issues in the tabs, with the difference that I am able to autocraft if machines are involved. Like Processors with "AE2 Stuff" for example. As long as its a machine pattern I can use it.

* **Issue**: Made a Pattern for Blank Patterns in Pattern Terminal. Tried with Certus Crystal AND Pure Certus Crystal. Then put it in the Interface and tried to craft it from Crafting monitor. Immediatly freezes all machines with "Waiting for server" but I still can move. Just cant click anything.

edit: for me refined EMC link is involved too, so removing it fixes the issue.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/74231042

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2

* **Known Fix**: --- remove refined EMC link while crafting.

**Comment by melbellrocks** [comment] 2019-03-29 03:37
See issue #84 for a temporary fix.

**Comment by Killersdaddy** [comment] 2019-03-29 17:45
Thanks a lot. Works fine :)

**Comment by Naxanria** [comment] 2019-04-04 15:57
Duplicate of #84

**Closed by Naxanria** 2019-04-04 15:57 UTC
