### ISSUE TITLE
Repeated Crashes from Matter Overdrive

### ISSUE THREAD

**Issue by Lost-Ninja** [FTBTeam/FTB-Sky-Odyssey#241] opened 2019-03-28 09:22 UTC
* 1.0.0 

* Many interactions with items from the Matter Overdrive: Legacy Edition. Mostly the weapons/batteries, but pretty much any interaction with them can cause a crash. All of the below are while trying to improve on weapons I've had as drops. Last two when I was trying to drop an upgraded Shotgun into a crate.

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/1626495a
https://paste.feed-the-beast.com/view/0837f291
https://paste.feed-the-beast.com/view/8de9136c
https://paste.feed-the-beast.com/view/ca1de222
Save file link: https://www.dropbox.com/s/b2vurghm9zeral3/MatterOverdriveCrashes.7z

* **Is it Repeatable?**: Yes... see above...

* **Mod/s Affected**: Matter Overdrive: Legacy Edition

* **Known Fix**:

**Comment by dsabecky** [comment] 2019-03-28 10:46
Duplicate of issue #230

**Comment by dsabecky** [comment] 2019-03-28 10:50
Similar to issue #240 and issue #54

**Comment by martinschuberteu** [comment] 2019-03-28 13:14
I also had a "java.lang.NullPointerException: Rendering screen at matteroverdrive.items.includes.EnergyContainer.getStackEnergyTag(EnergyContainer.java:74)" crash when putting a Battery into the Transmutation Table and searching for it. It doesn't seem to be repeatable though.

**Comment by Killersdaddy** [comment] 2019-03-31 11:55
The issue is, if you press "shift" on those weapons too often it will crash the game. For me its always on the third one if I dont wait like 5-7 sec. between shifting.

**Comment by Naxanria** [comment] 2019-04-05 15:43
Mod will be removed in next update.

**Closed by Naxanria** 2019-04-05 15:43 UTC
Labels: Sent to mod author, duplicate, fixed in dev
