### ISSUE TITLE
The game crashed whilst rendering screen issue.

### ISSUE THREAD

**Issue by NathanC123** [FTBTeam/FTB-Sky-Odyssey#230] opened 2019-03-26 21:43 UTC
Modpack Version: 1.0.0

Issue: Whenever I join a multiplayer server with my friend I have an issue where it crashes me after 2 minutes it says The game crashed whilst rendering screen. my friend does not have the same issue. does anyone know how to fix this?

 Crash File Paste    https://paste.feed-the-beast.com/view/150d87f0

Is it Repeatable?: Yes.

Mod/s Affected: -

Known Fix: -

**Comment by Rushmead** [comment] 2019-03-27 11:53
This is caused by the Phaser Rifle from Matter Overdrive. The bug has already been reported to the maintainers of Matter Overdrive. To fix the issue with logging in you may need to remove the item from your inventory by modifying your player data.

**Comment by NathanC123** [comment] 2019-03-27 18:41
thankyou

**Comment by Slowpoke101** [comment] 2019-04-05 13:06
This is going to be resolved in the next update as we are removing Matter Overdrive completely.

**Closed by Slowpoke101** 2019-04-05 13:06 UTC
Labels: Sent to mod author, bug
