### ISSUE TITLE
quantum solar crash

### ISSUE THREAD

**Issue by gupje20** [FTBTeam/FTB-Sky-Odyssey#110] opened 2019-03-20 20:58 UTC
[crash-2019-03-20_21.37.14-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/2990083/crash-2019-03-20_21.37.14-client.txt)

using builder wand on quatum solar pannel makes it spawn other panels after that it crashed and now it keeps crashing

**Comment by applemes** [comment] 2019-03-20 23:41
^ anytime I stare at a quantum solar panel with the unbreakable wand, the game crashes, and anytime i take the wand out afterwards it crashes, but to fix it you have to drop wand and get new one, but dont look at it again with wand out lol

**Comment by Naxanria** [comment] 2019-03-21 12:48
Duplicate of https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/102

**Comment by gupje20** [comment] 2019-03-21 12:57
yes that did the trick but there is still the problem with the want and the panels tho

**Closed** 2019-04-05 15:56 UTC
Labels: fixed in dev
