### ISSUE TITLE
Lava and water chicken eggs useless

### ISSUE THREAD

**Issue by vaalkaar** [FTBTeam/FTB-Sky-Odyssey#199] opened 2019-03-24 02:51 UTC
Not sure if it's a design change from the 1.10 version of chickens, but the lava and water eggs no longer act as buckets in machines and tanks.  Having to place the fluid in the world and then collect it seems like a step backwards.

**Comment by Naxanria** [comment] 2019-03-25 16:55
You could request the mod author to change the behavior of those eggs. 
But as they work as intended as in placing water/lava in the world, I am going to close this issue.

**Closed by Naxanria** 2019-03-25 16:55 UTC
