### ISSUE TITLE
Ender IO Game Crash 

### ISSUE THREAD

**Issue by nurdism** [FTBTeam/FTB-Sky-Odyssey#363] opened 2019-04-18 05:19 UTC
* **Modpack Version**: 1.1.0

* **Issue**: Game Crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/181d4580

* **Is it Repeatable?**: Seems to happen with big Vibrant Capacitor Banks, when holding an unbreakable BB wand.

* **Mod/s Affected**: Ender IO (maybe BB Wands)

**Comment by Ravenon** [comment] 2019-04-18 20:58
I ended up running into this bug as well.  Any time I try to log back in to the instance I get the last 2 reports.

-    Modpack Version: 1.1.0
-    Issue: Game Crash
-    Link to Log or Crash File Paste: 
          [crash-2019-04-18_14.29.03-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3096111/crash-2019-04-18_14.29.03-client.txt)
          [crash-2019-04-18_15.31.56-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3096112/crash-2019-04-18_15.31.56-client.txt)
          [crash-2019-04-18_15.35.05-client.txt](https://github.com/FTBTeam/FTB-Sky-Odyssey/files/3096113/crash-2019-04-18_15.35.05-client.txt) 
-    Is it Repeatable?: Seems to happen with big Vibrant Capacitor Banks, when building with a wand. Mine was the diamond wand.
-    Mod/s Affected: Ender IO

**Comment by Naxanria** [comment] 2019-04-19 07:21
Duplicate of #353

**Closed as completed by Naxanria** 2019-04-19 07:21 UTC
Labels: duplicate
