### ISSUE TITLE
Remove EMC from Time in a Bottle

### ISSUE THREAD

**Issue by ParseThePotatoes** [FTBTeam/FTB-Sky-Odyssey#273] opened 2019-04-02 15:17 UTC
* **Modpack Version**: Sky Odyssey 1.0.0

* **Issue**: I've accidentally fed my Time in a Bottle to my transmutation tablet twice, and have almost fed it multiple times.  Most tools - from diamond hoes to red matter picks - if you accidentally EMC-ify them, you can pull out the same tool again.  However, when you pull a new Time in a Bottle from the transmutation table, it (understandably) doesn't keep the stored time it had when added.  As all of its ingredients have EMC, it's easy enough to craft a new one if you accidentally trash or drop your bottle.  
As a quality-of-life change, could EMC be removed from the Time in a Bottle?

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**:  Yes, you can feed multiple time in a bottles (times in a bottle?) to a tablet, and any pulled bottles have no stored time.

* **Mod/s Affected**: N/A

* **Known Fix**: Add randomthings:timeinabottle to custom_emc.json with an EMC of 0

**Comment by Naxanria** [comment] 2019-04-02 15:49
This is a good life lesson, dont put everything into the table :)
As this is intended behaviour. Closing it.

**Closed by Naxanria** 2019-04-02 15:49 UTC
Labels: Working as Intended

**Comment by twothe** [comment] 2019-05-13 14:05
Please reconsider this issue.

When putting a big amount of items in your tablet by dragging via Mouse Tweaks you can easily hit an item like the Time in a Bottle and add it as well involuntarily. Usually high-value items do not have EMC (or it doesn't matter because they have no NBT info), but the Time in a Bottle is an exception. This can easily lead to mistakes, and the fix is simple.
