### ISSUE TITLE
Game Crash while crafting wireles terminal + crafting terminal

### ISSUE THREAD

**Issue by Easyjo4** [FTBTeam/FTB-Sky-Odyssey#263] opened 2019-03-31 12:33 UTC
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Easyjo4** [comment] 2019-03-31 12:34
Game crashed while crafting in Me craft. terminal

**Comment by Naxanria** [comment] 2019-03-31 12:37
duplicate of #165

**Closed by Naxanria** 2019-03-31 12:37 UTC
Labels: duplicate
