### ISSUE TITLE
Crashing on world load

### ISSUE THREAD

**Issue by VolcanoCookies** [FTBTeam/FTB-Sky-Odyssey#203] opened 2019-03-24 10:48 UTC
* **1.0.0**: 

* **Crashing with ArrayOutOfBounds: 814 when near, or placing solar panels**: 

* **https://paste.feed-the-beast.com/view/fdd5979d**: 

* **Yes, once it happens it will happen every time i start that specific world. Only way ive found to fix it temporarily is to remove the solar panels in mcedit.**: 

* **Techrebord**: 

* **Remove the solar panels in MCedit, only encountered when placing ca 1-2 stacks of solar panels, current ones i used were quantum **:

**Comment by Naxanria** [comment] 2019-03-25 17:00
Duplicate of #102 and #110

**Closed by Naxanria** 2019-03-25 17:00 UTC
Labels: bug, duplicate
