### ISSUE TITLE
Factory controller (@woot) did not trigger the quest

### ISSUE THREAD

**Issue by AlexTeplyh** [FTBTeam/FTB-Sky-Odyssey#235] opened 2019-03-27 13:32 UTC
* **Modpack Version**: 1.0.0

* **Issue**: When I crafted Factory controller it was not counted. I think it is NBT issue. screenshot http://joxi.ru/vAWd3b4Tgkw3xr

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: woot, ftb quests/shop

* **Known Fix**: I think it should ignore NBT, so it can be counted

**Comment by sLpFhaWK** [comment] 2019-03-28 03:20
I just made one for an Enderman and it also did not trigger the quest.

**Comment by dsabecky** [comment] 2019-03-28 08:57
duplicate of issue #78

**Closed** 2019-03-28 10:40 UTC
Labels: duplicate
